name: Deploy Shopify Theme and notify slack

on:
  push:
    branches: [ master ]
jobs:
  shopify:
    name: Shopify
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install themekit
        run: curl -s https://shopify.github.io/themekit/scripts/install.py | python
      - name: Print env
        run: env
      - name: Deploy shopify theme
        run: cd src; theme deploy
